version: '3.9'

services:
  walletdb:
    image: postgres:16
    container_name: WalletDb
    ports:
      - "5455:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: WalletDb
    volumes:
      - walletdb_data:/var/lib/postgresql/data
    restart: unless-stopped

  wallet-api:
    build:
      context: .
      dockerfile: ./src/01-API/Wallet.Api/Dockerfile
    container_name: WalletApi
    ports:
      - "5000:80"
    depends_on:
      - walletdb
    environment:
      - ConnectionStrings__DefaultConnection=Host=walletdb;Port=5432;Database=WalletDb;Username=admin;Password=admin123
    restart: unless-stopped

volumes:
  walletdb_data:
    external: false